default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "^app/"
      - id: end-of-file-fixer
        files: "^app/"
      - id: check-merge-conflict
        files: "^app/"
      - id: debug-statements
        files: "^app/"

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: "^app/"

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: "^app/"
        exclude: ^.*\b(alembic)\b.*$

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        files: "^app/"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
        files: "^app/"
      - id: python-check-blanket-noqa
        files: "^app/"
